baseURL                = "https://ice-energy.github.io/user1"
languageCode           = "en-us"
defaultContentLanguage = "en"
title                  = "UserOne Docs n Recs"
theme                  = "mainroad"
paginate               = "8"
canonifyURLs           = false

#disqusShortname = ""
enableRobotsTXT  = true
enableEmoji      = true

[Author]
	name           = "User One"
	bio            = "Computer Nerd, Closet Font Enthusiast, Aspiring Golf League Website Designer"
	avatar         = "img/user1.png"
        about          = true

[Params]
        description      = "User1 repository for Docs and Other info"
	subtitle         = "Technical Documents, Roadmaps, Treasures, and a few Random Thoughts"
        opengraph        = true
        twitter_cards    = false
        readmore         = false
        leftsidebar      = false    # Move sidebar to the left side if true
        authorbox        = true     # Show authorbox at bottom of pages if true
        post_navigation  = true     # Show post navigation at bottom of pages if true
        postSections     = ["post"] # the section pgs to show on HomePg and Recent articles" widget
       #postSections     = ["blog", "news"] # alternative that shows more than one section's pages
       #dateformat       = "2006-01-02" # change the format of dates

       #enableToc        = true
       #enableShareCard  = true

[Params.widgets]
    search              = true  # Enable "Search" widget
    recent_articles     = true  # Enable "Recent articles" widget
    recent_articles_num = 5     # Set the number of articles in the "Recent articles" widget
    categories          = true  # Enable "Categories" widget
    tags                = true  # Enable "Tags" widget
    tags_counter        = false # Enable counter for each tag in "Tags" widget (disabled by default)

    #social_facebook     = "username"
    #social_twitter      = "username"
    social_linkedin      = "user1"
    social_github        = "ice-energy/user1"
    social_email         = "user1@ice-energy.com"
    #social_google_plus  = "profileid"


